### ISSUE TITLE
Redesign the Rocket League page

### ISSUE THREAD

**Issue by Maizuou** [Maizuou/Maizu#9]
Look for potential new images and GIFs to use for the page and make it appealing

1. Come up with a redesign
2. get necessary images and GIFs
3. Implement them in the HTML and replace the old ones that are not in use anymore
4. Redo the structure for the page in the CSS
5. Make it resizable and scalable
6. Check the HTML and CSS for any necessary changes needed

**Comment by abitsalihu** [comment]
Hey @Maizuou, I would like to work on this issue. :)

**Comment by Maizuou** [comment]
> Hey @Maizuou, I would like to work on this issue. :)

Hello @abitsalihu , you can fork and edit the main branch. Feel free to make a pull request and I will create a second branch for testing. Every help is appreciated. <3
